---

- name: prepare folder
  file:
    name: "{{ _target }}"
    state: directory
    mode: u=rwX

- name: download
  get_url:
    url: "{{ _url }}"
    dest: "{{ _target }}/{{ _craften_launcher_archive }}"

- name: unarchive
  unarchive:
    src: "{{ _target }}/{{ _craften_launcher_archive }}"
    dest: "{{ _target }}"
    remote_src: true
